### ISSUE TITLE
Modeling for AdminMetadata/Provenance Data

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#13]
This isn't an issue with the RML, but it will be an issue with the output. We're currently, as Theo says, making two sets of AdminMetadata for each URI. One for the RDA, one for the BIBFRAME. We do want administrative metadata about both...but since it's attached to the URI there's nothing connecting the Admin metadata to the right set of triples. Is this why SVDE started using N-quads? I'm not sure how else we're going to get around this issue. Theo's email:

We're planning this: 
```
<https://trellis.sinopia.io/repository/washington/018e4c97> a bf:Work, rdac:Work ;
    bf:adminMetadata [ a bf:AdminMetadata ;
                       #enter RDA adminMetadata triples ] ;
                     [ a bf:AdminMetadata ;
                       #enter BF adminMetadata triples ] .
```
Pretty weird! For example, which adminMetadata block is describing what triples?
_

One idea (stolen from Gordon Dunsire's Presentation "RDA models for Provenance Data" at the RDA Steering Committee's working group meeting in August 2016) is to make our RDA description set into an entity so we can talk about it, then use RDA properties rather than BF properties in the future. **As a quick-fix for the data we currently have, we can attach the AdminMetadata for the BF directly to the URI's, and attach the AdminMetadata for the RDA to a new URI for the description set which is a named graph. Maybe a DOI in line with what we've been doing with the Semantic Web data?** Here's a snippet from [Dunsire's presentation](http://www.rda-rsc.org/sites/all/files/RSC-TechnicalWG-1.pdf) (begins on p.5):
## Provenance:
An "RDA data statement" is a single metadata statement about an instance of an entity giving a value for some aspect of the individual instance. The statement may be formatted in various ways, for example as a name-value pair attached to the instance, or as a single RDF triple.

An "RDA data set" is a group of RDA data statements, usually linked in chains and clusters, and often with a specific individual instance as the focus of the metadata.

## RDA data set
The general provenance of an RDA data set is modelled in RDA using the *description of...* subject relationship designators in the template:  
Entity has -- description (entity) -- RDA Data Set.  
This applies to any RDA entity:  
Manifestation has a description (Manifestation) RDA Manifestation Data Set.  
The Data Set is treated as a Work, with its own related entities. General provenance data describe the data set:
- RDA Manifestation Data Set has creator Person (in the role of cataloguer)
- RDA Manifestation Data Set is realized by Expression
   - Expression has language of expression (French)
   - Expression is embodied in Manifestation
      - Manifestation has date of publication "2016"

RDA Manifestation Data Set is a type of Work.  
The provenance data can be simplified by using the non-FRBR (unconstrained) RDA elements available in the RDA Registry:  
- RDA Manifestation Data Set has creator Agent (in the role of cataloguer)
- RDA Manifestation Data Set has language of the content <French>
- RDA Manifestation Data Set	has date of publication “2016”

The method is recursive:
- RDA Manifestation Data Set has description (expression) RDA Manifestation Data Set Expression Data Set

In linked data applications, the RDA Data Set is a "named graph"; that is, it has a URI that identifies a set of one or more triples.  
The provenance data applies only the specific instance of the data set. "Record-level" provenance data in shared cataloguing systems can be accommodated by treating the "record" as an integrating or serial Work, with each instance a separate iteration.  
Data set provenance data are not automatically inherited by the component data statements. For example, the creator of the data set is not assumed to be the creator of the individual data statements in the set.
## RDA data statement
Provenance data for individual RDA statements is modelled using the same method:
- RDA Data Statement has creator Agent
- RDA Data Statement has language of thee content 
- RDA Data Statement has date of publication

These are the non-FRBR, unconstrained RDA properties. The refinement of a FRBR approach is not required for most applications.

**Comment by CECSpecialistI** [comment]
@briesenberg07 's response to @gerontakos 's email:

I’m still unsure about <iri> a rdac:Work, bf:Work .

I just want to make sure that I understand the implications--the biggest issue in my mind is the requirement for the following statement for Sinopia entities:

<iri> sinopiavocab:hasResourceTemplate <rtiri> 

If we have as a goal putting re-useable BF into Sinopia, I’m not sure that we would do a service to anyone by making our resources “double-sized,” needing a double-sized resource template (RDA + BF props for a given resource) to properly be displayed and manipulated in the Linked Data Editor.

That being said, not doing as Theo said (<iri> a rdac:Work, bf:Work) would surely involve many many challenges to do with creating new IRIs for one or the other, BF or RDA resources, making the new IRIs for WEMI/WWII link properly, getting them back into Sinopia, etc. etc.

Ben

**Comment by CECSpecialistI** [comment]
The conversation with Jeremy is clear as mud. I think I didn't do a good job explaining what we're trying to do. Ack. I don't 100% understand what he's saying either. Anybody have translation suggestions?



Crystal Clements  11:21 AM
Hi Jeremy! We are trying to put RDA data provenance into our RDA data rather than using the bf:AdminMetadata. To do this, we need to turn our RDA/RDF data sets into named graphs so we can make statements about them. Are we allowed to load named graphs into Sinopia? Will it break anything?
11:22
Basically each description set created by a resource template would need to be turned into a named graph instead of a bunch of triples.

Jeremy Nelson  11:44 AM
Hi Crystal, would the RDA data provenance be a separate resource template that would be saved as a resource?

Crystal Clements  11:56 AM
we haven't gotten that far but presumably yes
11:56
or, no
11:57
I'm not sure.
11:58
we want to know whether we can use named graphs before deciding how to model the data provenance

Jeremy Nelson  12:07 PM
Sinopia currently loads and generates quads of existing resource but that is more of an artifact of the Javascript RDF library we’re using.
12:11
The new Sinopia API persists the resource as serialized JSON-LD like https://api.development.sinopia.io/resource/7438f178-80ba-4d45-842e-2eb20b259c8e in the MongoDB document’s data property.

Crystal Clements  12:15 PM
are quads and named graphs the same thing?

Jeremy Nelson  12:16 PM
I believe quads are how you support named graphs (triple + graph identifier) (edited) 

Crystal Clements  12:20 PM
ok that's my understanding too :slightly_smiling_face: So if we upload in the format you've given it will be possible for us to use named graphs/quads in Sinopia?

Jeremy Nelson  12:24 PM
I think I don’t really understand your question, how specifically do you imagine using named graphs? When editing a resource Sinopia doesn’t use RDF, the RDF is generated only when loading, previewing or saving.

Crystal Clements  12:30 PM
Right. It's hard to explain because our idea of how we want to use it is kind of amorphous right now. Sorry, thanks for taking the time to answer my convoluted question!
We currently have a lot of description sets loaded in Sinopia using RDA properties. Each description set is created using a resource template that has a bf:AdminMetadata resource template embedded in it via a property template.
We are transforming our RDA into BIBFRAME with the intention of loading the BIBFRAME into Sinopia via http. So, we will have two descriptions of each URI we create to describe a resource, one in RDA/RDF and one in BIBFRAME. They will each have AdminMetadata. But, given the current model, there will be nothing connecting the AdminMetadata to the right description set. So, we want to change the way we talk about our RDA data by using RDA data provenance, which relies on RDA triples being put into named graphs so that statements can be made about them. I don't think the provenance statements themselves would be part of a named graph. We're trying to figure out whether this is possible.
We have an internal Github issue about it, but the group thought it would be a good idea to reach out to you all first to see whether the solution we're considering is possible.
https://github.com/uwlib-cams/rml/issues/13 (edited) 

Jeremy Nelson  12:38 PM
I think if you have a separate resource template for the RDA data provenance, you could reference that resource through it’s URI in your RDA description.

Jeremy Nelson  12:43 PM
This is the approach other institutions are using with AdminMetadata being a separate resource with a URI that is then linked with to it’s described resource. See https://development.sinopia.io/editor/ld4p:RT:bf2:Monograph:Instance:Un-nested for an example of a Work that has a lookup for a separate AdminMetadata resource.

Crystal Clements  12:51 PM
The problem is that the RDA and BIBFRAME descriptions are sharing a URI
12:52
so it will look like this:
12:52
https://trellis.sinopia.io/repository/washington/018e4c97 a bf:Work, rdac:Work ;
bf:adminMetadata [ a bf:AdminMetadata ;
#enter RDA adminMetadata triples ] ;
[ a bf:AdminMetadata ;
#enter BF adminMetadata triples ] .

Jeremy Nelson  12:58 PM
Why couldn’t you have two AdminMetadata templates, one BIBFRAME and one RDA, in the resource’s AdminProperty property?

Crystal Clements  1:55 PM
we can...that's what we're kind of doing now. But, we won't know what AdminMetadata goes with which triples.
1:56
because we'll have two sets of triples.

**Comment by gerontakos** [comment]
This is a difficult topic. For me the most difficult question is about what the RDA provenance data model would look like. If we knew that, we would know what to ask for, or maybe at least it would be easier for me to read the conversation with J Nelson. I'm not sure just having named graphs provides the solution we want. 

The main problem I see with the RDA model for meta-metadata (data provenance) is that it's relatively easy (using quads) to make statements about description sets, but difficult to make descriptions about individual statements. Do we want to go ahead and just create the ability to make statements about description sets only?

Here's what I'm thinking it will look like:
**TriG representation**
_Example 1 … gives  the ability to describe the full description set only._
<http://all-our-description-sets.uw.edu/descriptionSet001>    {
      <work999> a rdac:Work ;
            rdaw:preferredTitleForWork “Greatest Work Ever” ;
            unknown:describedBy <http://all-our-description-sets.uw.edu/descriptionSet002> 
} 
http://all-our-description-sets.uw.edu/descriptionSet002    {
    <work888>  a  rdac:Work ;
            rdaw:hasAuthorPerson  <<http://someBaseUri/cec.23>	;
            ex:encodingLevel  "full" ;
            rdaw:hasSubject  <work999> .
}
Example 2 … I don’t have. We would need a named graph for every single statement … enabling us to make specific statements about specific statements.
Example 3 … I don’t have, maybe reified RDF? There’s the widely hated reification in the original RDF Primer; there’s also  Wikibase-style but that may be overkill. Probably other methods…

Any thoughts? I think you're correct Crystal, we just want to go for quads and descriptions of description sets.

**Comment by CECSpecialistI** [comment]
@gerontakos I don't think we should make each statement into its own named graph. I don't know of a reason why we would want to get this granular with meta-metadata...I'm happy with description-set-level data provenance, and defining "description set" as the statements generated from a resource template.

**Comment by gerontakos** [comment]
First, I believe this is not an RML issue. We're looking for a way in Sinopia to trash our bf:AdminMetadata RT in favor of using RDA properties to describe "data provenance." If we do that, then we'll have an RML issue: what to do with the W-E-M entities that are descriptions of description sets. Do those triples have a direct mapping to BF? If so, how do we represent that in our mapping then, of course, how do we write the RML code. But actually getting the RDA data provenance into Sinopia has nothing to do with RML.

So we might want to eliminate this as an RML issue.  

I'll move the discussion outside Github for now, how about into Teams. However let's leave the issue open, anticipating that this issue will in fact become an RML issue -- or not, and then we can close it.

**Comment by briesenberg07** [comment]
# See [adminMetadataInSinopia.docx](https://uwnetid.sharepoint.com/:w:/s/og_library_cams/EcJ3kIMnGFFOo3_P56Y2sRkBwsUf_wRBc_U_4_YwweZgpA?e=kF4Hbg)

**Comment by CECSpecialistI** [comment]
We decided to move this discussion to future iterations of our RDA-RDF profiles, but not include in current RML/RDA2BF2 mapping discussions. Closing issue.
