### ISSUE TITLE
housekeeping - code snippets in issues

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/rml#14]
Just a kind of housekeeping note to say that I can't really make heads of tails of the RDF snippets posted here, for example in #6 :

>> bf:contribution
bf:Contribution
<rdf:type rdf:resource="http://id.loc.gov/ontologies/bflc/PrimaryContribution"/>
bf:agent
<bf:Agent rdf:about="http://id.loc.gov/authorities/names/n81008294">
<rdf:type rdf:resource="http://id.loc.gov/ontologies/bibframe/Person"/>
bflc:name00MatchKeyStani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903,</bflc:name00MatchKey>
bflc:primaryContributorName00MatchKeyStani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903,</bflc:primaryContributorName00MatchKey>
bflc:name00MarcKey1001 $6880-01$aStani︠u︡kovich, K. M.$q(Konstantin Mikhaĭlovich),$d1843-1903,$eauthor.$0http://id.loc.gov/authorities/names/n81008294$0http://viaf.org/viaf/sourceID/LC|n81008294</bflc:name00MarcKey>

...and in #5 ...

>> bf:source
bf:Source
<rdf:type rdf:resource="http://id.loc.gov/ontologies/bibframe/Agent"/>
rdfs:labelCSL</rdfs:label>
</bf:Source>
</bf:source>
bf:descriptionLanguage
<bf:Language rdf:about="http://id.loc.gov/vocabulary/languages/eng">
bf:codeeng</bf:code>
</bf:Language>
</bf:descriptionLanguage>

...by @CECSpecialistI . They seem quite garbled to me and I can't really tell what I'm supposed to be seeing lots of the time. Is there some other format that could be used? Thank you!

**Comment by briesenberg07** [comment]
>@briesenberg07 that's the format Alma outputs for the BIBFRAME. I can start translating it to something else for sure.

Wait you mean that Alma's BF output isn't even well-formed XML? Like, from above:
>`rdfs:labelStani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903,</rdfs:label>`

**Comment by CECSpecialistI** [comment]
i'm looking at it in the viewer so that might be the issue; you have to run an export job to output the file properly so some punctuation is missing...i'm so used to looking at it that i didn't notice :/

**Comment by CECSpecialistI** [comment]
aaaand now that i'm looking at it, it appears to be there? is it inconsistent? argh

**Comment by CECSpecialistI** [comment]
example:
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:bf="http://id.loc.gov/ontologies/bibframe/" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:bflc="http://id.loc.gov/ontologies/bflc/" xmlns:madsrdf="http://www.loc.gov/mads/rdf/v1#">
<bf:Work rdf:about="https://open-na.hosted.exlibrisgroup.com/alma/01ALLIANCE_UW/bf/entity/99162334560201452#Work">
      <bf:adminMetadata>
         <bf:AdminMetadata>
            <bf:generationProcess>
               <bf:GenerationProcess>
                  <rdfs:label>DLC marc2bibframe2 v1.6.0-SNAPSHOT: 2020-09-28T23:19:54+00:00</rdfs:label>
               </bf:GenerationProcess>
            </bf:generationProcess>
            <bf:identifiedBy>
               <bf:Local>
                  <rdf:value>99330154392501451</rdf:value>
                  <bf:assigner>
                     <bf:Agent rdf:about="http://id.loc.gov/vocabulary/organizations/dlc"/>
                  </bf:assigner>
               </bf:Local>
            </bf:identifiedBy>
            <bf:status>
               <bf:Status>
                  <rdfs:label>corrected or revised</rdfs:label>
                  <bf:code>c</bf:code>
               </bf:Status>
            </bf:status>
            <bflc:encodingLevel>
               <bflc:EncodingLevel rdf:about="http://id.loc.gov/vocabulary/menclvl/f">
                  <rdfs:label>full</rdfs:label>
               </bflc:EncodingLevel>
            </bflc:encodingLevel>
            <bf:descriptionConventions>
               <bf:DescriptionConventions rdf:about="http://id.loc.gov/vocabulary/descriptionConventions/isbd">
                  <rdfs:label>isbd</rdfs:label>
               </bf:DescriptionConventions>
            </bf:descriptionConventions>

**Comment by CECSpecialistI** [comment]
but yeah it's ugly and I can make my examples not so hideously difficult to read :)

**Comment by briesenberg07** [comment]
Thank you for looking into this @CECSpecialistI ! Any double-checking of Alma code snippets posted in issues is much appreciated, because they help me to know exactly what we are talking about.
