### ISSUE TITLE
Multiple instances of the same contribution property

### ISSUE THREAD

**Issue by mcm104** [uwlib-cams/rml#17]
Here's a snippet of our source data:
```
    <rdae:P20275>Archer, Phil</rdae:P20275>
    <rdae:P20275>Baker, Tom</rdae:P20275>
    <rdae:P20275>Miller, Libby</rdae:P20275>
```

A brief, non-technical explanation for how RML works: so for this mapping, I have three different chunks of RML code for each of the three blank nodes we need: bf:Contribution, bf:Agent, and bf:Role. For each of those chunks of code, I write it so that it either:
A) processes all instances of rdae:P20275 at once (putting everything into one blank node), or
B) processes each instance of rdae:P20275 separately (putting each into its own blank node)
 
However, because we have a blank node within a blank node, I need to write in for both bf:Contribution _and_ bf:Agent whether to split or not (in RML code, this means processing three separate times, or processing once). And that makes things funky. (bf:Role at least is easy -- we only process once!)
 
So if neither is split (bf:Contribution is only processed once, bf:Agent is only processed once), we get:
```
bf:contribution [ a bf:Contribution ;
                     bf:agent [ a bf:Agent ;
                                   rdfs:label "Archer, Phil",
                                              "Baker, Tom",
                                              "Miller, Libby" ] ;
                     bf:role [ a bf:Role ;
                                  rdfs:label "writer of foreword"@en ] ] .
```
_All the agents in one bf:Agent, all in one bf:Contribution._

If bf:Agent is split but bf:Contribution is not (bf:Contribution is only processed once, bf:Agent is processed three times), we get this, which I see as currently our best option:
```
bf:contribution [ a bf:Contribution ;
                    bf:agent [ a bf:Agent ;
                                 rdfs:label "Baker, Tom" ],
                             [ a bf:Agent ;
                                 rdfs:label "Miller, Libby" ],
                             [ a bf:Agent ;
                                 rdfs:label "Archer, Phil" ] ;
                    bf:role [ a bf:Role ;
                                rdfs:label "writer of foreword"@en ] ] .
```
_bf:Agents are separate, and all housed in the same bf:Contribution_
 
If bf:Contribution is split but bf:Agent is not (bf:Contribution is processed three times, bf:Agent is only processed once), we get this:
```
ns1:contribution [ a ns1:Contribution ;
                     ns1:agent [ a ns1:Agent ;
                                   rdfs:label "Archer, Phil",
                                              "Baker, Tom",
                                              "Miller, Libby" ] ;
                     ns1:role [ a ns1:Role ;
                                  rdfs:label "writer of foreword"@en ] ],
                [ a ns1:Contribution ;
                    ns1:agent [ a ns1:Agent ;
                                  rdfs:label "Archer, Phil",
                                             "Baker, Tom",
                                             "Miller, Libby" ] ;
                    ns1:role [ a ns1:Role ;
                                 rdfs:label "writer of foreword"@en ] ],
                [ a ns1:Contribution ;
                    ns1:agent [ a ns1:Agent ;
                                  rdfs:label "Archer, Phil",
                                             "Baker, Tom",
                                             "Miller, Libby" ] ;
                    ns1:role [ a ns1:Role ;
                                 rdfs:label "writer of foreword"@en ] ] .
```
_All agents in one bf:Agent, but there are three bf:Contributions_
 
And if bf:Contribution and bf:Agent are both split (bf:Contribution is processed three times, bf:Agent is processed three times), we get:
```
ns1:contribution [ a ns1:Contribution ;
                     ns1:agent [ a ns1:Agent ;
                                   rdfs:label "Miller, Libby" ],
                               [ a ns1:Agent ;
                                   rdfs:label "Archer, Phil" ],
                               [ a ns1:Agent ;
                                   rdfs:label "Baker, Tom" ] ;
                     ns1:role [ a ns1:Role ;
                                  rdfs:label "writer of foreword"@en ] ],
                 [ a ns1:Contribution ;
                     ns1:agent [ a ns1:Agent ;
                                   rdfs:label "Miller, Libby" ],
                               [ a ns1:Agent ;
                                   rdfs:label "Archer, Phil" ],
                               [ a ns1:Agent ;
                                   rdfs:label "Baker, Tom" ] ;
                     ns1:role [ a ns1:Role ;
                                  rdfs:label "writer of foreword"@en ] ],
                 [ a ns1:Contribution ;
                     ns1:agent [ a ns1:Agent ;
                                   rdfs:label "Miller, Libby" ],
                               [ a ns1:Agent ;
                                   rdfs:label "Archer, Phil" ],
                               [ a ns1:Agent ;
                                   rdfs:label "Baker, Tom" ] ;
                     ns1:role [ a ns1:Role ;
                                  rdfs:label "writer of foreword"@en ] ] .
```
_bf:Agents are separate, but all three are in each of the three bf:Contributions_
 
SO. We can either go with the best option listed above ("option B"), or I could reach out to the RML devs to see if there's some way to get our ideal mapping to work, which we decided was this:
```
bf:contribution [ a bf:Contribution ;
                    bf:agent [ a bf:Agent ;
                                 rdfs:label "Baker, Tom" ];
                    bf:role [ a bf:Role ;
                                 rdfs:label "writer of foreword"@en ] ] ;
bf:contribution [ a bf:Contribution ;
                    bf:agent [ a bf:Agent ;
                                 rdfs:label "Miller, Libby" ];
                    bf:role [ a bf:Role ;
                                rdfs:label "writer of foreword"@en ] ] ;
bf:contribution [ a bf:Contribution ;
                    bf:agent [ a bf:Agent ;
                                 rdfs:label "Archer, Phil" ];
                    bf:role [ a bf:Role ;
                                rdfs:label "writer of foreword"@en ] ] .
```
Thoughts?

**Comment by briesenberg07** [comment]
Thank you for writing this out and making it easy to understand @mcm104 !

Judging solely from among *the BF output configurations which are currently possible*, I agree with you that the best choice seems to be:
```
bf:contribution [ a bf:Contribution ;
                    bf:agent [ a bf:Agent ;
                                 rdfs:label "Baker, Tom" ],
                             [ a bf:Agent ;
                                 rdfs:label "Miller, Libby" ],
                             [ a bf:Agent ;
                                 rdfs:label "Archer, Phil" ] ;
                    bf:role [ a bf:Role ;
                                rdfs:label "writer of foreword"@en ] ] .
```
*Is this "valid" or "proper" BIBFRAME? I'm not sure. And maybe that's okay!* It makes sense to me...

An aside--would we ever encounter a similar situation in which agents would need to be assigned different roles? 

Well, no, I suppose, because then literals would be values for differing properties, not the same one, as in your input example above:
```
    <rdae:P20275>Archer, Phil</rdae:P20275>
    <rdae:P20275>Baker, Tom</rdae:P20275>
    <rdae:P20275>Miller, Libby</rdae:P20275>
```
(Interesting to note that [E/P20275](http://rdaregistry.info/Elements/e/P20275) is a deprecated property--might be something we want to change in new Sinopia RTs.)

**Comment by CECSpecialistI** [comment]
I think it's "valid", but not "proper". I think as long as they're all coming from the same RDA property (and should have the same role label in BIBFRAME) we might be in the clear, but it's unconventional and I'm not sure how well it will match with the BIBFRAME others are creating. Which isn't a big concern right now but might be in the future if this is part of our workflow. I think for the sake of our own knowledge, and on the off chance that it prompts a change for the better in RML, it's worth reaching out to RML devs. What do you think @briesenberg07 and @gerontakos ?

E/P20275 is marked deprecated in the Registry because it won't be used in the new RDA, which we haven't yet implemented. So we still need to (and should) use it until we are cataloging using the new RDA. Since the rules for new RDA are so open-ended, I don't think it makes sense to use it to guide our profiles creation until we get a bit more guidance from the PCC...we can't write our own application profile with any hope that it will be close to what they come out with.

**Comment by gerontakos** [comment]
I don't see anything wrong with what Melissa calls our best option. It looks not only good but proper to me. We don't have to agree with absolutely everything everyone else does. What's improper here? You're concerned that this expression has 3 forewords? So what if it does? We're describing a a contribution whose role bears the label "writer of foreword." It doesn't matter if there are 1, 2,or 3 forewords, there's only one manner of contribution albeit with three different agents. I don't see how somebody querying the data would miss these three agents. True they may arrive at the book and say, oh nice, they didn't jointly write the foreword, they all wrote their own. But they'll find it.

I have no argument against using P20275.

**Comment by JianPLee** [comment]
I'm not sure if option B is good enough though. In the BIBFRAME resource template, it clearly indicates that only one contributor per contribution node. Will it cause error when doing the conversion?

**Comment by gerontakos** [comment]
Proposal: edit the BF RT?? Allow multiple agents per Contribution?

**Comment by briesenberg07** [comment]
> I'm not sure if option B is good enough though. In the BIBFRAME resource template, it clearly indicates that only one contributor per contribution node. Will it cause error when doing the conversion?

@JianPLee I'm curious which BIBFRAME RT you are referring to.

**Comment by JianPLee** [comment]
@briesenberg07 _Monograph Work (BIBFRAME)/ld4p:RT:bf2:Monograph:Work
![image](https://user-images.githubusercontent.com/69644644/96757585-7be5bb80-138a-11eb-9f56-3dbcdbde5e7d.png)

**Comment by JianPLee** [comment]
> Proposal: edit the BF RT?? Allow multiple agents per Contribution?

Interesting. I didn't realize we can do that. Is this means we create our own WAU:BF:RT ?

**Comment by gerontakos** [comment]
I see you mean the ld4p:RT:bf2:Monograph:Work; we can't edit that. However we can edit the RTs in the  WAU:BF2:* series. Our data, our resource templates, our rules. AnyoneCanSayAnythingAboutAnything.

**Comment by gerontakos** [comment]
Oops sorry that was too ambiguous; I mean I think we should edit our RT for our BF data to allow multiple agents per sontribution.
