### ISSUE TITLE
AdminMetadata bf:generationProcess bf:GenerationProcess rdfs:label

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#2]
It might be polite of us to generate a note on how and when we have generated our data once we're ready to start uploading it to Sinopia. For example, Alma lets us know it has used a specific version of LC's converter at a specific time:
_<bf:generationProcess>
               <bf:GenerationProcess>
                  <rdfs:label>DLC marc2bibframe2 v1.6.0-SNAPSHOT: 2020-09-21T19:45:44+00:00</rdfs:label>
               </bf:GenerationProcess>
            </bf:generationProcess>_
@mcm104 is there a way for us to accomplish this using python for all of our AdminMetadata? All of the bibframe I've looked at from other places has it and I've found it useful in other projects.

**Comment by mcm104** [comment]
Yes! We can insert any triples we want using rdflib. I've added the code for this to rml.py, and here's what it will look like in the output:
```
<https://trellis.sinopia.io/repository/washington/018e4c97-fb45-4333-9e8e-6cc0584e49ac> a bf:Work ;
    bf:adminMetadata [ a bf:AdminMetadata ;
            bf:generationProcess [ a bf:GenerationProcess ;
                    rdfs:label "rml.py SNAPSHOT: 2020-09-21T16:07:21+00:00" ] .
```
I based the label on your example from the LC converter, but we can format it however we want!

**Comment by CECSpecialistI** [comment]
You are magic!!!!

**Comment by CECSpecialistI** [comment]
I'm stoked on it as-is.
