### ISSUE TITLE
eek! Identifiers as literals and URI's

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#20]
It looks like in addition to having the odd literal value in a BF property that expects a URI, we also have some odd URI's in properties that are usually literals. For identifiers, for instance, we've got mostly typed literals, but some URI's. How do we want to form the resource templates for identifiers @mcm104 @briesenberg07 @JianPLee @gerontakos ? As URI/lookups (as we've decided to do with other stuff)? Or as typed literals (since most of the values here are typed literals)?

https://github.com/uwlib-cams/rml/blob/6aaf493f21b82bf0cde9865a02636342ad9fe934/output/2021_04_14/instance_ttl/02324962-673e-444f-8b54-f3d74ddaa7d2.ttl#L31

**Comment by CECSpecialistI** [comment]
For now I've done it as a typed literal. I don't know where that will leave things like full URI's for the doi referenced above though.

**Comment by gerontakos** [comment]
Let's find out; I think it will be one of the triples that appears "at the top" for which there is no place in the RT, no? That seems fine to me, if that's the case. I mean not forever, just "for now."

**Comment by CECSpecialistI** [comment]
I think the same thing. It just makes me wonder whether we need to make all of these things typed literals, or all of them lookups, or decide on a case-by-case basis?

**Comment by gerontakos** [comment]
Right, sorry, I meant that's what will happen when we do them all as typed literals (or, to be fussy, not really "typed literals" but literals in a bnode adjacent to an rdf:type property/value, I believe): _that seems fine (for now), let's do them all as typed literals._

**Comment by CECSpecialistI** [comment]
Done!
