### ISSUE TITLE
Variant titles have rdfs:label and mainTitle...do we need both?

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#21]
"Title" has a literal value for mainTitle and no rdfs:label with the same value. It appears that we've generated "VariantTitle" with identical literal values for both properties. Should it just be "mainTitle"?

https://github.com/uwlib-cams/rml/blob/be0a1d49df59cf6fc4bc47b0ba642903247e664a/output/2021_04_14/instance_ttl/024d9d14-1b89-4f3e-8891-acabad273b36.ttl#L44

**Comment by gerontakos** [comment]
I suspect the rdfs:label used with instances of bf:VariantTitle is a hangover from the times before the RDA access point became the official label. Based on that hunch, I would say yes, we should remove the label from instances of bf:VariantTitle. Another thing: I believe it's ok variant titles don't have a subtitle. (It looks like on the RDA, we entered main and sub title into "has variant title of manifestation" P30128, whereas we enter only the main title in "has title proper" P30156 with the subtitle in "has other title information" P30142. Fair enough.)

**Comment by mcm104** [comment]
I removed the rdfs:label from the kiegel for this property, so it won't be there in future outputs!

**Comment by CECSpecialistI** [comment]
hooray!!!

**Comment by gerontakos** [comment]
Monster!
