### ISSUE TITLE
Repeated classes with duplicate literal values where there should be properties

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#22]
bf:subject [ a madsrdf:Authority ;
madsrdf:Authority "label" ;
rdfs:label "sameLabel" ;
........

https://github.com/uwlib-cams/rml/blob/fbbbc92885ca0c6bbcbd8ffe42b57965709fbe26/output/2021_04_14/work_1_ttl/08466404-97e7-4e81-9551-63a5734c3880.ttl#L34

is the "madsrdf:Authority "label" ; " included in error?

**Comment by CECSpecialistI** [comment]
same thing is happening here: https://github.com/uwlib-cams/rml/blob/fbbbc92885ca0c6bbcbd8ffe42b57965709fbe26/output/2021_04_14/work_1_ttl/376e4c17-671c-43dc-8866-2b9a4802e497.ttl#L10-L12

**Comment by CECSpecialistI** [comment]
Perhaps something similar here? I don't know why these ones turned out this way while the other contribution agents I've seen didn't? 

https://github.com/uwlib-cams/rml/blob/fbbbc92885ca0c6bbcbd8ffe42b57965709fbe26/output/2021_04_14/work_1_ttl/38db605b-e971-49b7-8321-bf24b6fdd94c.ttl#L22-L27

**Comment by CECSpecialistI** [comment]
again here https://github.com/uwlib-cams/rml/blob/fbbbc92885ca0c6bbcbd8ffe42b57965709fbe26/output/2021_04_14/work_1_ttl/3aa16c7d-b23e-49f8-a95c-dd081af82831.ttl#L10-L13

**Comment by gerontakos** [comment]
I think these are all problems. I don't see anything to blame in the first problem associated with bf:subject mapped to w/P10256. The Kiegel looks good to me in [rda2bf-5.0](https://docs.google.com/spreadsheets/d/1IakSZQwN9Mq19oW-7ffoQ98h79U2csiUeC4BCsaFMBw/edit?usp=sharing).

The second one (creator characteristic) and the last one seem to be associated with [rda2bf_rdaExtension](https://docs.google.com/spreadsheets/d/1qSarnhzENkJOhIKDiZtHAIVZgTFNd_ZMUZnBl2TNsN8/edit?usp=sharing) where again I do not see problems with the Kiegel (bflc:creatorCharacteristic >> bflc:CreatorCharacteristic > rdfs:label).

The third one looks like bf:agent mapped to https://doi.org/10.6069/uwlib.55.d.4#hasContributorAgent in rda2bf_rdaExtension again; in this case, I see the capitalization error in the Kiegel: contribution >> Contribution > agent >> agent > rdfs:label. The contributor that's ok looks like it's well done but in rda2bf-5.0, not in the extension.

**Comment by mcm104** [comment]
I found the source of the issue for all of these except for [this one](https://github.com/uwlib-cams/rml/issues/22#issuecomment-820808549) -- the code I was using to determine if something was a class or not wasn't taking prefixes into account! That's been fixed now, so this will be fixed in future updates. Now investigating that last issue...

**Comment by gerontakos** [comment]
Ha ha why didn't I didn't fix the problem? I think, Melissa, you were testing us when you corrected the Kiegel to contribution >> Contribution > Agent >> agent > rdfs:label. Shouldn't it have been contribution >> Contribution > agent >> Agent > rdfs:label. **This time I'll go ahead and change it!** I hope I pass the test.

**Comment by mcm104** [comment]
Yes, you've solved my Kiegel puzzle 😅

**Comment by CECSpecialistI** [comment]
Yay! Thanks @mcm104 and @gerontakos ! Are we ready to close this issue?
