### ISSUE TITLE
Dissertation bnodes should be combined?

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#23]
within the property bf:dissertation for a bf:Work, we have split out the properties into separate blank nodes. They should probably be all together in one bnode, yeah?
https://github.com/uwlib-cams/rml/blob/fbbbc92885ca0c6bbcbd8ffe42b57965709fbe26/output/2021_04_14/work_1_ttl/23774eca-7c54-4aec-aeb6-bec65386896c.ttl#L30

**Comment by gerontakos** [comment]
Yes, I agree; you can see why it happened: they're all on separate rows in the rda2bf-5.0 spreadsheet, all including a bnode. If mcm104 can fix it relatively easily, I think it's worth it. There's another case that this fix would apply to, in addition to "has degree granting institution," "has academic degree," and "has year degree granted": "has dissertation or thesis information" w/P10209, mapped to bf:note >> bf:Note etc.

**Comment by mcm104** [comment]
I've added a fix so that P10006 (has degree granting institution), P10077 (has academic degree), and P10215 (has year degree granted) all end up in the same bf:Dissertation blank node, but I'm a little unclear about Theo's addition -- do you mean that this note should also be in the blank node, like:

```
bf:dissertation [ a bf:Dissertation ;
    bf:grantingInstitution <P10006value> ;
    bf:degree "P10077value" ;
    bf:date "P10215value" ;
    bf:note [ a bf:Note ;
        rdfs:label "P10209value" ;
        bf:noteType "dissertation or thesis information" ]
] .
```
?

**Comment by CECSpecialistI** [comment]
I like  P10006 (has degree granting institution), P10077 (has academic degree), and P10215 (has year degree granted) all going into the same bNode and could take or leave the note being included in the bnode along with them. Is that what you meant @gerontakos ?
