### ISSUE TITLE
blank literals

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#24]
Nodes with blank literals like this one should probably be deleted entirely. Is that easy to do?

https://github.com/uwlib-cams/rml/blob/fbbbc92885ca0c6bbcbd8ffe42b57965709fbe26/output/2021_04_14/work_1_ttl/24673a05-3e9e-4f69-8307-f9412bdf6433.ttl#L23

**Comment by gerontakos** [comment]
that's freak-o weird. In the RDA-RDF the property/relationship is http://uw.edu/adaptationProperties/p/w/derivativeWorkRelationships. What's that? thing that it's related to (requires a bnode) is types as http://uw.edu/adaptationProperties/c/w: what's that?? And then there's some others weird stuff:
[
 {
      "@id": "https://api.sinopia.io/resource/66de3ff5-2b1c-41b6-a25b-8a30b6a2b69f",
      "@type": [
        "http://rdaregistry.info/Elements/c/C10001"
      ],
 "http://uw.edu/adaptationProperties/p/w/derivativeWorkRelationships": [
        {
          "@id": "_:b0"
        }
      ]
},
{
      "@id": "_:b0",
      "@type": [
        "http://uw.edu/adaptationProperties/c/w"
      ],
      "http://rdaregistry.info/Elements/w/P10148": [
        {
          "@id": "_:b1"
        }
      ]
},
{
      "@id": "_:b1",
      "@type": [
        "http://uw.edu/adaptationProperties/c/w"
      ],
      "http://rdaregistry.info/Elements/w/P10155": [
        {
          "@id": "_:b2"
        }
      ]
},
{
      "@id": "_:b2",
      "@type": [
        "http://uw.edu/adaptationProperties/c/w"
      ],
      "http://rdaregistry.info/Elements/w/P10025": [
        {
          "@id": "http://id.loc.gov/authorities/names/n2015062306"
        }
      ]
}
]

**Comment by mcm104** [comment]
This looks like test data from when we were trying out the failed nested profiles for adaptation properties, so any issues here can probably just be ignored. If you see that rdfs:label "" anywhere else, let me know, but to me it just looks like the result of trying to transform janky data.

**Comment by CECSpecialistI** [comment]
Is this test data something we want to delete from Sinopia? Or should we just leave it there since it's just Stage?
