### ISSUE TITLE
Multiple Contributors need multiple bf:Contribution, bf:Agent nodes

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#25]
https://github.com/uwlib-cams/rml/blob/ae70dce044a9da13caef4ec6ef6848d7f6f6b3d6/output/2021_04_14/work_1_ttl/447eec01-25c2-46ec-a54a-f8c481a3e77a.ttl#L20-L29

should be: 
 bf:contribution [ a bf:Contribution ; 
                             bf:agent [ a bf:Agent ; 
                                             rdfs:label "Kontokostas, Dimitris" ] ;
                             bf:role <http://id.loc.gov/vocabulary/relators/aut ] ;
bf:contribution [ a bf:Contribution ; 
                             bf:agent [ a bf:Agent ; 
                                             rdfs:label "Boneva, Iovka" ] ;
                             bf:role <http://id.loc.gov/vocabulary/relators/aut ] ;
bf:contribution [ a bf:Contribution ; 
                             bf:agent [ a bf:Agent ; 
                                             rdfs:label "Prud'hommeaux, Eric" ] ;
                             bf:role <http://id.loc.gov/vocabulary/relators/aut ] ;
bf:contribution [ a bf:Contribution ; 
                             bf:agent [ a bf:Agent ; 
                                             rdfs:label "Labra Gayo, Jose Emilio" ] ;
                             bf:role <http://id.loc.gov/vocabulary/relators/aut ] ;

**Comment by CECSpecialistI** [comment]
also have this one, which might be correct bibframe but is different from both the shapes of bibframe in this issue 
https://github.com/uwlib-cams/rml/blob/ae70dce044a9da13caef4ec6ef6848d7f6f6b3d6/output/2021_04_14/work_1_ttl/5d3df716-3cdd-47f4-8be7-4a5c6ea2b594.ttl#L22-L29

**Comment by CECSpecialistI** [comment]
these are inconsistent too:
https://github.com/uwlib-cams/rml/blob/ae70dce044a9da13caef4ec6ef6848d7f6f6b3d6/output/2021_04_14/work_1_ttl/81160840-d9fe-4376-b669-812de648d5d7.ttl#L21-L40

**Comment by gerontakos** [comment]
I don't see a problem with any of those; they all look like sound RDF to me, and an accurate mapping. Let's discuss before anything gets changed. I'll put it on the next meeting agenda for the next meeting Tues Apr 20.

**Comment by mcm104** [comment]
This is something we discussed in the last round of data review -- I wrote up an explanation of what the mapping is doing here https://github.com/uwlib-cams/rml/issues/17 . This issue happens when multiple contributing agents have the same role -- when they have different roles, it works in the ideal way.

**Comment by CECSpecialistI** [comment]
Sorry, I should have remembered/looked up that old issue! It's odd looking but not technically incorrect...and I just tested it in Sinopia and our resource templates can hold the data this way. Closing in favor of #17 , which we can probably close too after briefly discussing today?
