### ISSUE TITLE
Missing Contributions

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#26]
I checked this in Sinopia to make sure it was indeed missing and not a cataloger error. The resource, [https://api.sinopia.io/resource/5112fda2-2a63-4d0a-8b02-1e7da4ebd85b](url), has lookup values from LCNAF for "has author agent" and "has book artist agent". The RDF looks right in the Sinopia preview. How did these triples get lost?

<https://api.sinopia.io/resource/5112fda2-2a63-4d0a-8b02-1e7da4ebd85b> <http://rdaregistry.info/Elements/w/P10254> <http://id.loc.gov/rwo/agents/nr94023259>.
<http://id.loc.gov/rwo/agents/nr94023259> <http://www.w3.org/2000/01/rdf-schema#label> "Melhorn-Boe, Lise, 1955-".
<https://api.sinopia.io/resource/5112fda2-2a63-4d0a-8b02-1e7da4ebd85b> 
    <http://rdaregistry.info/Elements/w/P10061> <http://id.loc.gov/authorities/names/n78074810>.
<http://id.loc.gov/authorities/names/n78074810> <http://www.w3.org/2000/01/rdf-schema#label> "Crozier, Lorna, 1948-". 

This is all that remains in our BF output:

https://github.com/uwlib-cams/rml/blob/ae70dce044a9da13caef4ec6ef6848d7f6f6b3d6/output/2021_04_14/work_1_ttl/bd2f8725-9e07-45c0-81bc-2cbc5f8b41bf.ttl#L41-L42

**Comment by CECSpecialistI** [comment]
This one [https://api.sinopia.io/resource/15381424-2eda-4d58-ad47-b1029e784398](url) has a missing contribution for a degree supervisor. Hmm.

**Comment by CECSpecialistI** [comment]
Another example of an author being present in Sinopia but not in BF output: https://api.sinopia.io/resource/16a61969-3b31-4e09-bba0-0319a13895d1

**Comment by CECSpecialistI** [comment]
But then some contributions are there. Such as this one: https://api.sinopia.io/resource/88ae0700-dd55-4089-add1-314469a85c12

Side note: I'm seeing a number of unused triples in our RDA resources. Have we been removing property templates from the RDA RT's?

**Comment by CECSpecialistI** [comment]
Here's a weird one... one contribution looks fine and the other one is missing.

https://github.com/uwlib-cams/rml/blob/ae70dce044a9da13caef4ec6ef6848d7f6f6b3d6/output/2021_04_14/work_2_ttl/2f5373ff-ee2d-431a-b2da-71aba975ebf3.ttl#L23-L26

https://github.com/uwlib-cams/rml/blob/ae70dce044a9da13caef4ec6ef6848d7f6f6b3d6/output/2021_04_14/work_2_ttl/2f5373ff-ee2d-431a-b2da-71aba975ebf3.ttl#L45-L46

**Comment by mcm104** [comment]
I found the issue -- the contribution blank nodes are written as a special case scenario, and I didn't accommodate IRIs correctly -- that's why it's been janky for authors with an IRI instead of a literal. It'll be fixed going forward!

Also, we've been ignoring and are now removing those triples where it's like, <authorIRI> rdfs:label "author label", so if that information is missing, it's supposed to be like that.

Not sure what you're referring to as "unused triples in our RDA resources"

**Comment by CECSpecialistI** [comment]
Hooray! Thanks Melissa! I shouldn't have even included unused triples in this issue I can show them during the meeting it's probably not even an RML related thing at all.
