### ISSUE TITLE
BIBFRAME metadata (RML output) should have an accurate bf:creationDate in bf:adminMetadata

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/rml#27]
Currently we see this RDA/RDF:
      <> bf:adminMetadata [ a bf:AdminMetadata ;
                  bf:creationDate "2019-11-27"^^xsd:date ] .
...output as the following in BIBFRAME:
      <> ns2:adminMetadata [ a ns2:AdminMetadata ;
                  ns2:creationDate "2019-11-27"@eng ] .
That is to say, the RDA.bf:creationDate is the same as the BIBFRAME.bf:creationDate.
However the BIBFRAME, derived from the RDA/RDF,  was created on a later date.
Can the python/rml output the date of creation of the BIBFRAME specifically?

Worth nothing: this applies to the first transformation of a specific RDA/RDF dataset. When, or if, the dataset is transformed again to incorporate some edits, the date of that second transformation is no longer a bf:creationDate but a bf:changeDate. Although incorporating this fix for the April/May 2021 POST to Sinopia is overambitious, it may be something we want to remedy in future RDA-2-BIBFRAME.

**Comment by mcm104** [comment]
Creation date is now edited to current date during transformation!
