### ISSUE TITLE
adminMetadata problem: bf:descriptionAuthentication not in BIBFRAME data

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/rml#28]
In our RDF/RDF, we see the following:
        <> ns2:adminMetadata [ a ns2:AdminMetadata ;
            ns2:descriptionAuthentication <http://id.loc.gov/vocabulary/marcauthen/pcc> ] .

It's not outputting to BIBFRAME produced by python/rml.

We should probably make that happen.

**Comment by mcm104** [comment]
This was missing in previous version of generateRML code -- it has now been added in the latest rewrite ([link to code](https://github.com/uwlib-cams/rml/blob/345a5d340e5bb4d3804500421dcf7c79598ff5f9/generateRML/admin_metadata_functions.py#L148))
