### ISSUE TITLE
Labels for Works/Expressions/Manifestations/Items

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#3]
I love that we've added labels to WEMI entities. The one I looked at for a Work seems to be using the bf:mainTitle. These are sometimes stuff like "Short stories. 1940." or "Poems." For this one it's "Short stories. Selections"@eng. There are 3,807 of those in Alma. Substituting bf:mainTitle with a combination of the primary contribution agent label and the mainTitle would make the labels more useful by reducing duplication. Or, since we're still including authorized access points, the authorized access points would be ideal since they have to be unique.

**Comment by gerontakos** [comment]
That's a good idea: the label for the resource is the AAP; if that is not present, use the title. @mcm104 can we make that change?

**Comment by mcm104** [comment]
Just realized I implemented this and didn't tell anyone -- yes! I just had to rewrite the kiegel.
