### ISSUE TITLE
bf:generationProcess in BIBFRAME takes a literal value that gets incorrectly typed

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/rml#30]
The value of bf:generationProcess in the BIBFRAME adminMetadata is output is a literal. Example:
   bf:generationProcess [ a bf:GenerationProcess ;
          rdfs:label "rml.py SNAPSHOT: 2021-04-14T14:05:31+00:00"^^xsd:dateTime ] .
That full literal is typed as xsd:dateTime. It is not a valid dateTime. 

Perhaps remove the type info?

**Comment by mcm104** [comment]
Code to determine datetype has been updated to be more precise, but currently only xsd:date values are being typed (see #29).
