### ISSUE TITLE
BIBFRAME in Sinopia issue: Admin metadata: Description authentication property displays in Sinopia RT.

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/rml#33]
For some reason, a "Description authentication" property with no value displays in Sinopia RTs. True for BF Items, Instances, and Works.

**Comment by CECSpecialistI** [comment]
That's a weird one. I can't see anything in the WAU:BF2:AdminMetadata RT that would make that happen. Could it be leftover from an older iteration of the RT? Eek.

**Comment by CECSpecialistI** [comment]
@mcm104 would you check the ID for the admin metadata resource template the RML code is using? We have several, but only one of them should be used (WAU:BF2:AdminMetadata)

**Comment by mcm104** [comment]
The RML code is not using any admin metadata RT -- see [detailed reply here](https://github.com/uwlib-cams/rml/issues/32#issuecomment-865373212)

**Comment by mcm104** [comment]
Adding tag @CECSpecialistI to make sure you've seen this!

**Comment by CECSpecialistI** [comment]
"Description authentication" is an option for authenticated descriptions (pcc or CONSER, for example) but isn't usually present. Since it's an option, it displays in Sinopia but doesn't get into the data itself unless it's needed.
