### ISSUE TITLE
BIBFRAME in Sinopia issue: WAU:RT:BF2:Classification RT nests inside the bf:Item classification property no matter what.

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/rml#35]
WAU:RT:BF2:Classification RT nests inside the classification property even if the value is an LCC number in a WAU:RT:BF2:LCC RT.

This was only noticed in one item, namely https://api.sinopia.io/resource/ea3c0026-c109-4e9e-9f2f-8aac27ae4f5b, so it may not be a problem for all items. Other items were not checked.

**Comment by CECSpecialistI** [comment]
Is this a problem? This is how I thought things needed to be. If they should be different, how should they look @gerontakos ?

**Comment by gerontakos** [comment]
I can't tell re-open this evening. After I search in sinopia.io, I select "View" (the eyeball icon) and I get the following message with a light red background: "A suppressible template must have one property template." 

As I remember it, the problem with this is that the value of bf:classification for this bf:Item was typed as bf:ClassificationLcc but in the RT is displays as bf:Classification in the bf:Classification RT. But since I cannot see it tonight I'm not totally sure.

**Comment by CECSpecialistI** [comment]
I fixed the issue making it impossible to open stuff, can you see now?

**Comment by gerontakos** [comment]
We can call it fixed; however if the fix is easy, let's fix. The problem appears to be the same as we saw for bf:identifiedBy in issue #40. 

The value of bf:classification is two nested RTs:
(1) WAU:RT:BF2:Classification. This is of course empty because it is not used here.
(2) WAU:RT:BF2:LCC. This is the correct RT with the correct value.

**Comment by CECSpecialistI** [comment]
The empty RT is just part of the Sinopia display because it's an option to add it. Since it is empty, it doesn't cause any problems. You can see when you preview RDF that the data doesn't include the other RT that's possible here. Since we cannot repeat property templates in the same RT in Sinopia, there's no way to avoid the display looking like this.
