### ISSUE TITLE
BIBFRAME in Sinopia issue: BF Items have incorrect values for bf:itemOf. Also: bf:itemOf does not display in Sinopia RT.

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/rml#36]
The property itemOf correctly appears in the BF Item RT and the correct sub-RT (WAU:RT:BF2:Instance) displays, but the value does not display. It appears correctly in the json-ld. True for BF Items.

A related issue: bf:itemOf values appear to be incorrect. Two examples:
In Sinopia:
<https://api.sinopia.io/resource/ea3c0026-c109-4e9e-9f2f-8aac27ae4f5b> a bf:Item;
    bf:itemOf <https://api.sinopia.io/resource/40145a5f-2c0a-4a6a-924c-af9efd105615> .
[Note: bf:itemOf only displays in JSON-LD.]
That resource however is an RDA Manifestation;
the item in question is most likely an itemOf < https://api.sinopia.io/resource/3934ee78-8555-4fca-bf15-192a3e92b1bf> .

In Sinopia:
<https://api.sinopia.io/resource/89bd121d-cb23-46f2-836f-6048a352fc3f> a bf:Item ;
    bf:itemOf <https://api.sinopia.io/resource/fe62d997-66df-4c28-b874-9aa862b1555d>.
[Note: bf:itemOf only displays in JSON-LD.]
That resource however is an RDA Manifestation;
the item in question is most likely an itemOf <https://api.sinopia.io/resource/1e6cfa13-1dba-44c7-b31d-cc7c0175a380>.
I checked this in the RML repo output 2021-05-04:
    there this item is <https://api.stage.sinopia.io/resource/5c865bdc-4d25-44c9-8fc8-07ef4890c8f0>
    ...where it correctly references the bf:Instance <https://api.stage.sinopia.io/resource/49f56f6c-1319-4499-be51-760a332bb9c9>.
    So that seems correct!

**Comment by mcm104** [comment]
Found the error for the incorrect bf:itemOf statements -- it has now been corrected, and I imagine it's going to fix several of the other issues as well. Will confirm and then load the corrected data into Sinopia.

**Comment by CECSpecialistI** [comment]
The resource templates look good to me. I just made the Instance RT suppressible, which might help. @mcm104 @gerontakos can we revisit this one after the next transform to see if that resolved the issue?

**Comment by mcm104** [comment]
New transformed data was loaded into Sinopia on 5/25 -- I'm not sure if it needs to go again for your change to take effect, but for what it's worth, I tried to view <https://api.sinopia.io/resource/89bd121d-cb23-46f2-836f-6048a352fc3f> in Sinopia and got this error message: "A suppressible template must have one property template."

**Comment by CECSpecialistI** [comment]
Gah! There has to be a cruddy resource template in there somewhere. I will look through them to root it out today.

**Comment by CECSpecialistI** [comment]
The cause of this error message is fixed.

**Comment by gerontakos** [comment]
I'll review the two items referenced at the beginning of the issue.

**(1) https://api.sinopia.io/resource/ea3c0026-c109-4e9e-9f2f-8aac27ae4f5b**
_Does the bf:itemOf property have the correct value?_
No, it does not; the value of bf:itemOf is a nested RT WAU:RT:BF2:Instance with no values (although properties display).

**(2) https://api.sinopia.io/resource/89bd121d-cb23-46f2-836f-6048a352fc3f** 
_Does the bf:itemOf property have the correct value?_
No, same as above.

It looks like this in the "view":
![itemOf](https://user-images.githubusercontent.com/6956200/122487562-6adc6100-cf90-11eb-82dc-a58649926397.PNG)

Or like this in the "Edit":
![itemOfEdit](https://user-images.githubusercontent.com/6956200/122487593-7af44080-cf90-11eb-95d0-fb46e9cb691b.PNG)

**Comment by mcm104** [comment]
I'm looking at the WAU:RT:BF2:Item RT -- is there a reason for nesting the WAU:RT:BF2:Instance RT here? I would expect it to be a URI or a lookup

**Comment by mcm104** [comment]
Adding tags @CECSpecialistI @gerontakos to make sure you've seen this!

**Comment by CECSpecialistI** [comment]
Yes that was a silly error on my part. I fixed the RT and hopefully it solves this issue.

**Comment by mcm104** [comment]
It looks fixed to me!

(1) For <https://api.sinopia.io/resource/ea3c0026-c109-4e9e-9f2f-8aac27ae4f5b>:
![itemOf1](https://user-images.githubusercontent.com/50182013/124990301-0774aa80-dff5-11eb-951e-aef568aaa95b.PNG)

(2) For <https://api.sinopia.io/resource/89bd121d-cb23-46f2-836f-6048a352fc3f>:
![itemOf2](https://user-images.githubusercontent.com/50182013/124990342-15c2c680-dff5-11eb-8ea2-fea64306c5cd.PNG)

**Comment by gerontakos** [comment]
Yes it looks great! Super! Thank you both! No disaster here (yet again).
