### ISSUE TITLE
BIBFRAME output problem: identifier >> barcode value described as English

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/rml#37]
Item > identifier >> Barcode > barcode value is tagged as "English." Note: it is also tagged as English in the RDA-RDF data.

**Comment by CECSpecialistI** [comment]
It would be nice if we could turn off language tagging for certain literal property templates. We could request?

**Comment by mcm104** [comment]
I edited the RML so it doesn't look for language tags for barcodes anymore, so the newest BIBFRAME (now in Sinopia) is no longer tagged as English! Doesn't fix the RDA though, so Crystal's suggestion may be a good thing to bring up!

**Comment by CECSpecialistI** [comment]
Thanks Melissa! Yes the RDA is a different beast. I just made a request that they allow us to make these decisions at the property template level: https://github.com/LD4P/sinopia_editor/issues/2837
