### ISSUE TITLE
BIBFRAME in Sinopia issue: no Classification info in bf:Instance

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/rml#39]
Classification info for <https://api.sinopia.io/resource/1e6cfa13-1dba-44c7-b31d-cc7c0175a380> does not display in Sinopia RT; it does however display in the JSON-LD. This is likely a problem for all bf:Instance that have classification data.

**Comment by CECSpecialistI** [comment]
This should now be fixed. I added classification to the bf:Instance template.

**Comment by mcm104** [comment]
I tried opening this resource in Sinopia and got two error messages:
"A suppressible template must have one property template."
"The following referenced resource templates are not available in Sinopia: WAU:RT:BF2:Identifier"

**Comment by CECSpecialistI** [comment]
Since these are the same error messages we're getting in another issue, I'm going to go ahead and close this one.
