### ISSUE TITLE
Datatypes for Dates

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#4]
Folks over at Sinopia are having trouble converting their dates properly in their BF2MARC conversion because their dates are still typed as literals. We have ours typed as literals here. It's poop. We suggested to catalogers to input their creation dates as edtf. We need to figure out what we're doing with dates at some point. Ex Libris/Alma (and so I assume LC) uses XML Schema. Should we?

<bf:changeDate rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2020-07-13T07:01:21</bf:changeDate>
            <bf:creationDate rdf:datatype="http://www.w3.org/2001/XMLSchema#date">1994-09-22</bf:creationDate>

**Comment by mcm104** [comment]
I wrote up a Python script that could at least fix our already existing data -- it goes line by line looking for BF date properties, determines format ("YYYY" vs. "YYYY-MM" vs. "YYYY-MM-DD"), and adds the appropriate datatype. [I put some sample output here](https://github.com/uwlib-cams/rml/blob/master/type_dates_sample.ttl) -- if we like the look of it, I can run it on all our BF output!

**Comment by CECSpecialistI** [comment]
That looks great to me. Should we check and see if it breaks Sinopia? Or are we creating our BIBFRAME with other uses in mind?

**Comment by mcm104** [comment]
I don't think we've tried putting any of our BIBFRAME into Sinopia yet, since we don't have an application profile to open it with and see how it handles our data. We were talking about creating a BIBFRAME AP at one point but I can't remember why we stopped...

**Comment by briesenberg07** [comment]
> That looks great to me. Should we check and see if it breaks Sinopia? Or are we creating our BIBFRAME with other uses in mind?

We are still creating BIBFRAME with the idea of putting it into Sinopia for use. However we have not started doing this yet and I don't believe that we plan to until the Sinopia backend is fully transitioned from trellis to mongoDB. (And until we have come up with a method for doing so, etc.)

Also, yes, as @mcm104 mentioned, another consideration is creating BIBFRAME that will be as conformant as possible with stable Sinopia resource templates, ideally with resource templates that are "PCC-approved." (But these don't exist yet, and we haven't identified any others to model our BF on in the interim, and the idea that we will model our BF output to given resource templates might involve a new round of adjustments to our RML conversion code.)

**Comment by gerontakos** [comment]
Actually this is good. The BF ontology doesn't say anything about these literals except that they're instances of rdfs:Literal. So good, it's "fresh info" in our data. I hope the code has an "otherwise" or "else" condition that states what to do when the literal syntax is not recognized as any date type? Just allow it to remain an instance of rdfs:Literal without being a typed Literal?

**Comment by gerontakos** [comment]
Similar to Ben, I'd be surprised if these date types broke anything in Sinopia -- if they ever get loaded.

**Comment by CECSpecialistI** [comment]
Great; let's keep this solution and revisit if we run into problems.
