### ISSUE TITLE
BIBFRAME in Sinopia issue: work2 has incorrect bf:expressionOf va.ue

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/rml#41]
bf:Work derived from RDA Expression has incorrect reference to the Work expressed; specifically, the bf:expressionOf property points to an RDA Work. This was true for https://api.sinopia.io/resource/340a8a08-3546-4ff5-874e-d430162c576e and https://api.sinopia.io/resource/7c952071-7f3f-42c4-8743-656aa5b8fce3

**Comment by mcm104** [comment]
Fixed by edit mentioned in #36
