### ISSUE TITLE
BIBFRAME in Sinopia issue: Sinopia bnode identifiers display instead of string values for bf:subject

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/rml#42]
[this may be an old issue]
Subjects that are supposed to be string values are displaying incorrectly using the Sinopia RT; specifically, the bnode identifier displays rather than bf:subject >> madsrdf:Authority > rdfs:label  [string value here].  Instead it's bf:subject=N35f4d1a27f3f4368b75700454d1098da. This was observed for https://api.sinopia.io/resource/dda6fb21-7922-4b39-aacb-08fa35d4414d and  https://api.sinopia.io/resource/b120e588-2977-4ce2-95d3-03eb07cde01a.

**Comment by CECSpecialistI** [comment]
This issue was waiting on the "suppressible" development to arrive. I've fixed the WAU:RT:BF2:Works template and subjects should all display. One question: I can either include MADS:authoritativeLabel or rdfs:label. Which do we prefer?

**Comment by gerontakos** [comment]
Although it's not critical, I'd say rdfs:label. It's more widely understood.

**Comment by CECSpecialistI** [comment]
This should now be fixed. @gerontakos @mcm104 should we run transform again after we've tackled all these issues before closing them?

**Comment by gerontakos** [comment]
Let's close it! They stay in Github, easily available, if we want to view. But this is fixed, let's close it!
