### ISSUE TITLE
BIBFRAME in Sinopia issue: Variant titles do not display in bf:Work

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/rml#43]
bf:Work instances derived from RDA Work do not display variant titles. There's nothing at all in the RT describing the variant title. This was observed for https://api.sinopia.io/resource/dda6fb21-7922-4b39-aacb-08fa35d4414d and  https://api.sinopia.io/resource/b120e588-2977-4ce2-95d3-03eb07cde01a.

**Comment by CECSpecialistI** [comment]
The RT for Variant Title wasn't linked to the Works or Instance RT's. I have fixed this issue. I noticed here that the resource template with ID WAU:RT:BF2:Work is used. I just requested that this be deleted in favor of WAU:RT:BF2:Works. @mcm104 are these entered into the RML individually or looked up by class? If they are entered individually, would you switch the ID's?

**Comment by mcm104** [comment]
Just edited my code with the new RT ID -- I'll run the transform again and let you know how things are looking!

**Comment by mcm104** [comment]
Transform has been run and is now in Sinopia, but I'm getting errors when I try to open resources:

- "A suppressible template must have one property template."
- "The following referenced resource templates are not available in Sinopia: WAU:RT:BF2:Identifier"

So I can't confirm that the data looks how it's supposed to in Sinopia! The RT for bf:Work now says WAU:RT:BF2:Works at least, so once the above errors are resolved, we should be good!

**Comment by CECSpecialistI** [comment]
The identifier for the correct identifier template is "WAU:RT:BF2:Identifiers".

**Comment by CECSpecialistI** [comment]
I will look through the suppressible templates. I think they all have a property template?

**Comment by CECSpecialistI** [comment]
These error messages are now fixed.
