### ISSUE TITLE
Installing & Running RML Mapper

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/rml#44]
Hi @mcm104 \:

I'm wrapping two (2) things into one issue here:
1. Letting you know that I've suggested changes to [Installing & Running RML Mapper](https://docs.google.com/document/d/1ufe8nBblVOsVX0HGARHVScPS8arS7cnT0pGPumetdU4/edit#heading=h.ookdrgd5ahm)
2. Proposing that we move this into the repo as a markdown file to see what you think

**Comment by mcm104** [comment]
These instructions are part of the README in the gettingstarted repo: <https://github.com/uwlib-cams/rml/tree/master/getting_started> I've updated it to include the changes from the Google doc!

**Comment by briesenberg07** [comment]
@mcm104 your excellent documentation brings a tear of joy to my eye 💯
