### ISSUE TITLE
Resources in 2022-01-20-demo

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/rml#46]
Shouldn't the 3 resources in multiple_resources.xml be:
https://example.org/Resource1
https://example.org/Resource2
https://example.org/Resource3 ?

At present they're all https://example.org/Resource1.

It's a puzzling problem presented in the demo. I don't know how best to describe it to the RML people but I can keep looking at it and make some suggestions -- maybe. But first let's clear up my confusion on the source XML file as presented above.

**Comment by mcm104** [comment]
Oof, yes, you're right, that was a mistake on my part. I've updated the files and the README accordingly -- it hasn't really changed my overall conclusion, but the output does look slightly different (albeit still not what we want).
