### ISSUE TITLE
Contribution modeling

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#6]
RDA doesn't conceptualize contributions in the same way as MARC/BIBFRAME--that's put us in a bit of a pickle here. 

Our RDA input data has contributions listed simply and directly as relationships. It also gives authorized access points as strings. If there is a primary contributor, it will always be the first portion of the authorized access point. That might help us to figure out how to more accurately map from RDA to BIBFRAME. RDA doesn't differentiate between the first listed author (bf:primary contributor) and second listed author (bf:contributor) because really their roles are the same. But for MARC and BIBFRAME, it's important to distinguish the primary contributor from the rest. Ack!

Our BIBFRAME output lists single authors (bibframe primary contributors who belong in MARC 1XX fields) like this:

_bf:contribution [ a bf:Contribution ; 
            bf:agent [ a bf:Agent ;
                    rdfs:label "Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903" ] ; 
            bf:role <http://id.loc.gov/vocabulary/relators/aut> ]_ 

This is what Alma (LC Converter) has:

   _<bf:contribution>
         <bf:Contribution>
            **<rdf:type rdf:resource="http://id.loc.gov/ontologies/bflc/PrimaryContribution"/>**
            <bf:agent>
               **<bf:Agent rdf:about="http://id.loc.gov/authorities/names/n81008294">**
                  **<rdf:type rdf:resource="http://id.loc.gov/ontologies/bibframe/Person"/>**
                  <bflc:name00MatchKey>Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903,</bflc:name00MatchKey>
                  <bflc:primaryContributorName00MatchKey>Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903,</bflc:primaryContributorName00MatchKey>
                  <bflc:name00MarcKey>1001 $6880-01$aStani︠u︡kovich, K. M.$q(Konstantin Mikhaĭlovich),$d1843-1903,$eauthor.$0http://id.loc.gov/authorities/names/n81008294$0http://viaf.org/viaf/sourceID/LC|n81008294</bflc:name00MarcKey>
                  **<rdfs:label>Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903,</rdfs:label>**
                  <bf:identifiedBy>
                     <bf:Identifier>
                        <rdf:value rdf:resource="http://viaf.org/viaf/sourceID/LC|n81008294"/>
                     </bf:Identifier>
                  </bf:identifiedBy>
               </bf:Agent>
            </bf:agent>
            **<bf:role>
               <bf:Role>
                  <rdfs:label>author.</rdfs:label>
               </bf:Role>
            </bf:role>**
         </bf:Contribution>
      </bf:contribution>
      <bf:contribution>_

We don't need to bother with the match/marc keys, but I think they'll probably be used in any BF2MARC conversions created by the community and if we want to use them in the future to turn BF into MARC (so catalogers experimenting in linked data wouldn't have to catalog everything twice) it would be good to have all the marc/match keys. I think we're doing roles better than they are because we're using URI's instead of labels, **but** the range for bf:role is bf:Role, so we need to change the model for that too. bf:role bf:Role (uri for the relator term). Everything else though I think we should be mirroring. 

What to do?

**Comment by gerontakos** [comment]
If BF cared about "primary contributions," why wouldn't there be a corresponding property or class in the BF ontology? I would assert that this is neither BF nor RDA, just MARC, and it would be wise to move away from "primary contribution." I believe MARC records will validate without a 1XX, so ... ah well, everybody in the 7XX! 

This does bring up the role of bflc. I say bflc can go hang; Kevin Ford says it's mostly a trial ground for properties/classes that may go into the BF ontology. It's mostly stuff we can ignore unless we have specialized needs.

The value of bf:role does not need to by typed as a bf:Role if the value is an IRI.

It's nice that Alma adds the reference to the authority file, but it types it as a bf:Person, which is incorrect. Plus they left some rubbish punctuation to remain in the label. 

Alma BIBFRAME raises the question of, who cares what Alma says is "canonical" BF? Do we? Who is deciding this anyway? I don't know of anyone that's telling us what the best practice is for BF data. We're getting there! 

So is this still an issue? Let's talk @CECSpecialistI

**Comment by briesenberg07** [comment]
Just a kind of housekeeping note to say that I can't really make heads of tails of the RDF snippets posted here, for example...

>> bf:contribution
bf:Contribution
<rdf:type rdf:resource="http://id.loc.gov/ontologies/bflc/PrimaryContribution"/>
bf:agent
<bf:Agent rdf:about="http://id.loc.gov/authorities/names/n81008294">
<rdf:type rdf:resource="http://id.loc.gov/ontologies/bibframe/Person"/>
bflc:name00MatchKeyStani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903,</bflc:name00MatchKey>
bflc:primaryContributorName00MatchKeyStani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903,</bflc:primaryContributorName00MatchKey>
bflc:name00MarcKey1001 $6880-01$aStani︠u︡kovich, K. M.$q(Konstantin Mikhaĭlovich),$d1843-1903,$eauthor.$0http://id.loc.gov/authorities/names/n81008294$0http://viaf.org/viaf/sourceID/LC|n81008294</bflc:name00MarcKey>

...and in #5 ...

>> bf:source
bf:Source
<rdf:type rdf:resource="http://id.loc.gov/ontologies/bibframe/Agent"/>
rdfs:labelCSL</rdfs:label>
</bf:Source>
</bf:source>
bf:descriptionLanguage
<bf:Language rdf:about="http://id.loc.gov/vocabulary/languages/eng">
bf:codeeng</bf:code>
</bf:Language>
</bf:descriptionLanguage>

...by @CECSpecialistI . They seem quite garbled to me and I can't really tell what I'm supposed to be seeing lots of the time. Is there some other format that could be used? Thank you!

**Comment by CECSpecialistI** [comment]
@briesenberg07 that's the format Alma outputs for the BIBFRAME. I can start translating it to something else for sure.

@gerontakos BF is trying to be interoperable beyond libraries/GLAM institutions...so I think that's why they threw primary contribution into bflc. I'm happy not to include it though if that's what you all think is best! It's really just for MARC.

@gerontakos @briesenberg07 @mcm104 so, it looks like all we may need to do for these is to make sure bf:role has a value of bf:Role? Or should we talk more about primary contribution? If we're not using our BIBFRAME to create MARC records, we really don't need it, but if we're planning to do that at some point, I think we need it.

**Comment by gerontakos** [comment]
I think we should proceed with our BF as if there's no MARC in the future; if we get around to producing MARC, we can start thinking about using bflc to improve our MARC derived from BF.

As for bf:role, it does not need to be typed as bf:Role if the role is expressed as an iri. If the role is expressed as a literal, I think all our BF creates a bnode for the value of bf:role, types the bnode as bf:Role, then adds the literal role as the value of rdfs:label. So we should be ok there.

**Comment by briesenberg07** [comment]
# Side-issue / housekeeping
>@briesenberg07 that's the format Alma outputs for the BIBFRAME. I can start translating it to something else for sure.

Wait you mean that Alma's BF output isn't even well-formed XML? Like, from above:
>`rdfs:labelStani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903,</rdfs:label>`

**Comment by mcm104** [comment]
This seems like a mapping issue rather than an RML issue -- can this issue be closed? Or do we still need to discuss this on GitHub?

**Comment by gerontakos** [comment]
I cautiously say, yes, I think it can be closed. But maybe someone else knows otherwise?
