### ISSUE TITLE
Modeling for Identifiers

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#8]
**Access points**
Where did we come up with this model for access points? Is it a work-around because BIBFRAME does away with authorized/variant access points? If so, what is its purpose? If the goal is just to create BIBFRAME, I don't think it's needed. If we need it for conversion of our BF to MARC, are we proposing this model because it's simpler than all the bflc:name00MatchKey etc. stuff LC is doing and it would be really hard to generate that from our RDA data? I imagine the bf2marc conversion will need to be adjusted to accommodate this if that's our goal. Sorry I missed this conversation :/ Halp!

I think we should re-think our use of "source". RDA isn't a source of an authorized access point. It's a description standard used by catalogers to create an authorized access point. If this has "source" "RDA", then so does every other statement we make. I don't think we need a source here. Do we?

_bf:identifiedBy [ a bf:Identifier ; 
            bf:note [ a bf:Note ;
                    rdfs:label "Authorized access point"@en ;
                    bf:noteType "type of identifier"@en ] ;
            bf:source [ a bf:Source ;
                    rdfs:label "RDA"@en ] ;
            rdf:value "Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903. Short stories. Selections"@eng ],
        [ a bf:Identifier ;
            bf:note [ a bf:Note ;
                    rdfs:label "Variant access point"@en ;
                    bf:noteType "type of identifier"@en ] ;
            bf:source [ a bf:Source ;
                    rdfs:label "RDA"@en ] ;
            rdf:value "Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903. Rasskazy"@rus ] ;_

**Other identifiers**
***[BMR: See #15 regarding assigning subclasses to identifiers (and other resources)]***
bf:Identifier.subclass? Is that valid? Or, do we need to just call them a bf:Identifier and separate them into their own bnodes?
_bf:identifiedBy [ a bf:Identifier.subclass ;
            rdf:value "10.1007/978-3-319-69974-5", **This is a [DOI](https://id.loc.gov/ontologies/bibframe.html#c_Doi)** 
                "2017957185" ], **This is a [LCCN](https://id.loc.gov/ontologies/bibframe.html#c_Lccn)**
        [ a bf:Identifier ;
            bf:note [ a bf:Note ;
                    rdfs:label "Authorized access point"@en ;
                    bf:noteType "type of identifier"@en ] ;
            bf:source [ a bf:Source ;
                    rdfs:label "RDA"@en ] ;
            rdf:value "Progress in Science, Progress in Society (Conference) ( 2016 : Brussels, Belgium). Progress in science, progress in society. English"@en ],
        [ a bf:Identifier ;
            rdf:value "10.1007/978-3-319-69974-5", **This is a [DOI](https://id.loc.gov/ontologies/bibframe.html#c_Doi)** 
                "2017957185" ], **This is a [LCCN](https://id.loc.gov/ontologies/bibframe.html#c_Lccn)**
        [ a bf:Identifier ;
            bf:source [ a bf:Source ;
                    rdfs:label "10.1007/978-3-319-69974-5", **This is a [DOI](https://id.loc.gov/ontologies/bibframe.html#c_Doi)** 
                        "2017957185" ] ; **This is a [LCCN](https://id.loc.gov/ontologies/bibframe.html#c_Lccn)**
            rdf:value "10.1007/978-3-319-69974-5", **This is a [DOI](https://id.loc.gov/ontologies/bibframe.html#c_Doi)** 
                "2017957185" ] ;_ **This is a [LCCN](https://id.loc.gov/ontologies/bibframe.html#c_Lccn)**
Another example:
_bf:identifiedBy [ a bf:Identifier ;
            rdf:value "ISBN 8673462827",
                "ISBN 9788673462820" ],
        [ a bf:Identifier ;
            bf:source [ a bf:Source ;
                    rdfs:label "ISBN 8673462827",
                        "ISBN 9788673462820" ] ;
            rdf:value "ISBN 8673462827",
                "ISBN 9788673462820" ],
        [ a bf:Identifier.subclass ;
            rdf:value "ISBN 8673462827",
                "ISBN 9788673462820" ] ;_

**Comment by CECSpecialistI** [comment]
Another problem with the same area:
_[ a bf:Identifier ;
            bf:note [ a bf:Note ;
                    rdfs:label "Variant access point"@en ;
                    bf:noteType "type of identifier"@en ] ;
            bf:source [ a bf:Source ;
                    rdfs:label "RDA"@en ] ;
            **rdf:value "Li, Jingjing. There are fish in the river"@en,
                "Li, Jingjing. 河里有鱼"@en** ] ;_
The bolded rdf:values here are separate variant access points, but they are being output as different rdf:values for the same variant access point.

**Comment by gerontakos** [comment]
Ha ha ha, yes, I've always been a little skeptical about this; I posted to the BF listserv but nobody replied. I'll try to address all the issues you raise in the order you raised them above.

Where did we come up with this? I went into the desert 40 days/nights then returned to civilization with it, exhausted.

Its purpose is only to maintain a useful identifying string associated with the resource. It doesn't have anything to do with MARC.

It is a bit of a work-around, but I think you can make a case for using bf:source. Rather than do that however I can suggest this: let's use something suggested elsewhere: use the AAP as the label of the resource, and stop outputting the AAP as an identifier. Doesn't that sound like a good solution?

That doesn't solve what to do with variant access points. Create a second label? In this case, different VAPs won't get smashed together as multiple values for the same VAP -- that was wrong. However they may get smashed into a single label if we change our course. Give it a go?

**Comment by CECSpecialistI** [comment]
I like that solution @gerontakos . AAP as the label is a good idea. Variant access points...are there alternate labels? Can we just turn them into (separate) alternate labels for the resources?

**Comment by gerontakos** [comment]
OK, skos:altLabel. So be it.

So how do we change this @CECSpecialistI @briesenberg07 @mcm104 ?

I think I only need to change the rda-to-bibframe map; the RML will adjust automatically and we'll be "in business." Yes?

**Comment by briesenberg07** [comment]
Just attempting to catch up on this issue now. My favorite bit so far:

> I think we should re-think our use of "source". RDA isn't a source of an authorized access point. It's a description standard used by catalogers to create an authorized access point. If this has "source" "RDA", then so does every other statement we make. I don't think we need a source here. Do we?

I'm interested in taking a closer look at our use of `bf:source`/`bf:Source` in general in our mappings, and I agree that this is something specific to think about here. Your argument makes sense to me and I'm curious to hear what others say... 

(I probably need to read farther; I'll be back soon to catch up the rest of the way...)

**Comment by gerontakos** [comment]
I'm making the changes sometime in the next week or so. I have a few changes to make.

**Comment by briesenberg07** [comment]
Thank you @gerontakos ! :pray:

**Comment by mcm104** [comment]
@gerontakos is correct -- the place to change this is in the RML-to-BIBFRAME-map!

Also, regarding `bf:Identifier.subclass` -- it's less of a typo and more that this is literally the only instance of writing kiegel syntax this way in all of our mappings (`bf:`[property]`.subclass`), so I haven't accounted for it in the code yet, and I'm not sure how I would... For LCCN, this is solved by the fact we're using our extension properties `rdax:hasLcClassificationPartA` and `rdax:hasLcClassificationPartB` (ditto for NLM classification). In cases where we're just using RDA "has identifier" properties, however, I'm not sure what we would do. It doesn't look like you can use regex with RML, but we might be able to using [the function ontology](https://fno.io/spec/#ontology) (FNO) which RML is now compatible with -- I would have to dig into this before saying for certain.

For now, the new RML code is just ignoring this part of the kiegel, but if we want to include it, I can start reading up on FNO.

**Comment by briesenberg07** [comment]
Thank you for the follow-up @mcm104 \:

This is good to know--and I didn't know until now--that we are using `.subclass` as a kind of shorthand in our kiegel mappings to indicate that a resource should be typed as a subclass of the class preceeding. See:

* For **has manifestation of work** with literal value
   * `hasInstance >> Instance.subclass > rdfs:label`
* For **has identifier for expression** with literal value
   * `identifiedBy >> Identifier.subclass > rdf:value`
* Etc.

I'll start a new issue as a placeholder for this (for whenever we are ready to pursue it), as it is a separate issue from modeling our identifiers.

**Comment by mcm104** [comment]
If I understand correctly, all that's left with this issue relates to mapping, with the RML side of things moved to Issue #15 -- can this issue be closed?

**Comment by briesenberg07** [comment]
> If I understand correctly, all that's left with this issue relates to mapping, with the RML side of things moved to Issue #15 -- can this issue be closed?

There is a lot going on in this issue--seems like we were talking about at least three or four different things in here! But if needed changes for RML have been moved to other issues (#15, etc.), it seems like it'd be okay to close this.
