### ISSUE TITLE
Splitting (keeping distinct) bnodes

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/rml#9]
**IDENTIFIERS**
_[ a bf:Identifier ;
            bf:note [ a bf:Note ;
                    rdfs:label "Variant access point"@en ;
                    bf:noteType "type of identifier"@en ] ;
            bf:source [ a bf:Source ;
                    rdfs:label "RDA"@en ] ;
            **rdf:value "Li, Jingjing. There are fish in the river"@en,
                "Li, Jingjing. 河里有鱼"@en** ] ;_

The bolded rdf:values here are separate variant access points, but they are being output as different rdf:values for the same variant access point.

_Originally posted by @CECSpecialistI in https://github.com/uwlib-cams/rml/issues/8#issuecomment-696441787_
**TITLES**
The same issue is mirrored in the corresponding variant titles:
_bf:title [ a bf:VariantTitle ;
            **bf:mainTitle "There are fish in the river"@en,
                "河里有鱼"@en** ],
        [ a bf:Title ;
            bf:mainTitle "He li you yu"@zh ] ._

I can't find anything on id.loc that forbids having multiple values strung together in this way, but I haven't seen it done before and we might run into conversion issues later.

I went into Sinopia to see what they're doing with their profiles and this is what it looked like when I entered three variant titles into their BF:Work RT:
_<> <http://id.loc.gov/ontologies/bibframe/content> <http://id.loc.gov/vocabulary/contentTypes/txt>;
    <http://id.loc.gov/ontologies/bibframe/title> _:b3_c14n0, _:b3_c14n1, _:b3_c14n2;
    <http://sinopia.io/vocabulary/hasResourceTemplate> "ld4p:RT:bf2:Monograph:Work";
    a <http://id.loc.gov/ontologies/bibframe/Work>.
<http://id.loc.gov/vocabulary/contentTypes/txt> <http://www.w3.org/2000/01/rdf-schema#label> "text".
_:b3_c14n0 <http://id.loc.gov/ontologies/bibframe/mainTitle> "hi i'm a variant title"@eng;
    a <http://id.loc.gov/ontologies/bibframe/VariantTitle>.
_:b3_c14n1 <http://id.loc.gov/ontologies/bibframe/mainTitle> "o hey i'm a variant title too."@eng;
    a <http://id.loc.gov/ontologies/bibframe/VariantTitle>.
_:b3_c14n2 <http://id.loc.gov/ontologies/bibframe/mainTitle> "oh what's up i'm a variant title."@eng;
    a <http://id.loc.gov/ontologies/bibframe/VariantTitle>._

**SUBJECTS**
_bf:subject [ a <http://www.loc.gov/mads/rdf/v1#Authority> ;
            rdfs:label "Roadside plants -- Northwest, Pacific -- Identification",
                "Roadside plants -- Northwest, Pacific -- Pictorial works.",
                "Wild flowers -- Northwest, Pacific -- Identification",
                "Wildflowers -- Northwest, Pacific -- Pictorial works" ] ;_

 _bf:subject <http://id.loc.gov/authorities/subjects/sh2007101022>,
        <http://id.loc.gov/authorities/subjects/sh2010116720> ;_

**GENRE/FORM**
This one might not be an issue. Aside from needing to be a bnode typed bf:GenreForm, since this isn't a bunch of values for label but separate URI's, it might be okay? Please advise.
_ bf:genreForm <http://id.loc.gov/authorities/genreForms/gf2014026210>,
        <http://id.loc.gov/authorities/subjects/sh85008302> ;_

**WORKS (Work has part--Another work)**
This is what our conversion for a list of 4 sub-works came out looking like:

bf:hasPart [ a bf:Work ;
rdfs:label "Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903. Dva mori︠a︡ka",
"Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903. Kut︠s︡yĭ",
"Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903. Maksimka",
"Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903. Pobeg" ] ;

The issue with this is that it looks like one work with four labels, rather than four separate works. So, it should be output as:

bf:hasPart [a bf:Work ;
rdfs:label "Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903. Dva mori︠a︡ka"],
[a bf:Work ;
rdfs:label "Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903. Kut︠s︡yĭ"],
[a bf:Work ;
rdfs:label "Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903. Maksimka"],
[a bf:Work ;
rdfs:label "Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903. Pobeg"" ] ;

**CONTRIBUTIONS**
The example below looks like there are two writers of foreword: Dan (Daniel) Brickley (his URI is the id.loc one below), and a person with three names, "Phil Archer", "Tom Baker", and "Libby Miller". We need a bf:Contribution for each person unless these are all labels for the same person, in which case, we should choose one preferred label. 

_bf:contribution [ a bf:Contribution ;
            bf:agent <http://id.loc.gov/rwo/agents/no2010154579> ;
            bf:role [ a bf:Role ;
                    rdfs:label "writer of foreword"@en ] ],
        [ a bf:Contribution ;
            bf:agent [ a bf:Agent ;
                    rdfs:label "Archer, Phil",
                        "Baker, Tom",
                        "Miller, Libby" ] ;
            bf:role [ a bf:Role ;
                    rdfs:label "writer of foreword"@en ] ] ;_

**Comment by briesenberg07** [comment]
*I think this is the right issue for this... but I might title my issue
# Need to split blank nodes
## EXAMPLE 1: bf:place >> bf:Place
* Source data has [two values for P30088 / place of publication](https://github.com/uwlib-cams/rml/blob/a5086f584eef9ce4b9effb4f7657230a22d43468/input/2020_09_18/manifestation/5c35ef9b-be8e-4ef4-aa74-61759291e0f4.ttl#L30-L33)
* These are output as [two rdfs:label values for the same bf:Place bnode](https://github.com/uwlib-cams/rml/blob/a5086f584eef9ce4b9effb4f7657230a22d43468/output/2020_09_18/instance/5c35ef9b-be8e-4ef4-aa74-61759291e0f4.ttl#L56-L61) when they should be rdfs:label values for two bf:Place bnodes
```
            bf:place [ a bf:Place ;
                    rdfs:label "Boston"@en, "Toronto"@en ] 
[...]
```

**Comment by gerontakos** [comment]
Yes, these are incorrect. We ran into a similar problem with bnodes that needed to be "merged;" this time they need to be unmerged. Do you think you can fix this, mcm104? Do we need to discuss at the next meeting?

**Comment by mcm104** [comment]
Solution for splitting blank nodes is here! I ran a test with the first example and got this output:
```
@prefix bf: <http://id.loc.gov/ontologies/bibframe/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<https://trellis.sinopia.io/repository/washington/1079c5c0-7ecd-4fb0-a090-f5a4bcabdf94> a bf:Work ;
    bf:identifiedBy [ a bf:Identifier ;
            bf:note _:1 ;
            bf:source _:0 ;
            rdf:value "Li, Jingjing. 河里有鱼"@chi ],
        [ a bf:Identifier ;
            bf:note _:1 ;
            bf:source _:0 ;
            rdf:value "Li, Jingjing. There are fish in the river"@eng ] .

_:0 a bf:Source ;
    rdfs:label "RDA"@en .

_:1 a bf:Note ;
    rdfs:label "Variant access point"@en ;
    bf:noteType "type of identifier"@en .
```
Now the question:
I could apply these on a case-by-case basis to the rest of the examples in this thread,
OR
I could start using this split-bnode way of writing RML as the default method, and instances where we WOULD want different values in the same blank node could be the exception (this one would actually require less work, but maybe this problem isn't as pervasive as I think it is)

**Comment by briesenberg07** [comment]
From a logical standpoint, I'd say that the **default** would be:

* **When the value of an RDA property is output as the value of a statement on a bnode in BF, to output this bnode separately from those required for the values of any other RDA properties.**

I say this without even starting the process of inventorying RDA property values which, when present, would need to be output as values for statements on *the same* bnode as those for one or more other RDA properties.

This seems like it *has to be* the default. In the absence of a specified set (or set*s*, as I imagine we have) of RDA property values which should be output as values for statements on the same `_:bnodeX` in BF, there *is no meaningful* way to output RDA property values to the same BF bnode(s).

**Comment by mcm104** [comment]
Blank nodes are now split by default in new version of generateRML.py. See [generateRML's README](https://github.com/uwlib-cams/rml/tree/master/generateRML), **"No-split" blank nodes**.
